spring.application.name=auth
com.thelastimperial.auth.patterns.password=^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$
com.thelastimperial.auth.patterns.email=^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}$
com.thelastimperial.auth.rememberme.key=KEY
