spring.application.name=oauthserver

server.port=8081

com.thelastimperial.auth.oauthserver.jwk.id=asdf
com.thelastimperial.auth.oauthserver.jwk.publicKey=asdf
com.thelastimperial.auth.oauthserver.jwk.privateKey=asdf
com.thelastimperial.auth.oauthserver.newclient.tz=America/Los_Angeles
com.thelastimperial.auth.oauthserver.newclient.expiresDays=15
com.thelastimperial.auth.oauthserver.newclient.secretSize=20
com.thelastimperial.auth.oauthserver.newclient.clientSize=16
com.thelastimperial.auth.oauthserver.newclient.scopes=profile,openid,USER
