spring.application.name=oauthserver

server.port=8081

com.thelastimperial.auth.oauthserver.jwk.id=asdf
com.thelastimperial.auth.oauthserver.jwk.publicKey=asdf
com.thelastimperial.auth.oauthserver.jwk.privateKey=asdf
